apiVersion: batch/v1
kind: Job
metadata:
  name: scala-build-example-2
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: provisioner
        image: alpine/git
        args:
        - clone
        - https://github.com/arempter/makisu-example.git
        - /makisu-context
        - -b
        - update_app_1
        volumeMounts:
        - name: context
          mountPath: /makisu-context
      containers:
      - name: makisu
        image: gcr.io/uber-container-tools/makisu:latest
        imagePullPolicy: IfNotPresent
        args:
        - build
        - --push=index.docker.io
        - --modifyfs=true
        - -t=arempter/makisu-example:0.1
        - --registry-config=/registry-config/registry.yaml
        - --redis-cache-addr=redis:6379  
        - /makisu-context
        volumeMounts:
        - name: context
          mountPath: /makisu-context
        - name: registry-config
          mountPath: /registry-config
        - name: storage
          mountPath: /makisu-storage
      volumes:
      - name: context
        emptyDir: {}
      - name: registry-config
        secret:
          secretName: docker-registry-config
      - name: storage
        emptyDir: {}
